function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "keypad_DONE"};
	this.sidHashMap["keypad_DONE"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<Root>/Analog Input"] = {sid: "keypad_DONE:128"};
	this.sidHashMap["keypad_DONE:128"] = {rtwname: "<Root>/Analog Input"};
	this.rtwnameHashMap["<Root>/Chart"] = {sid: "keypad_DONE:113"};
	this.sidHashMap["keypad_DONE:113"] = {rtwname: "<Root>/Chart"};
	this.rtwnameHashMap["<Root>/Data Store Read"] = {sid: "keypad_DONE:148"};
	this.sidHashMap["keypad_DONE:148"] = {rtwname: "<Root>/Data Store Read"};
	this.rtwnameHashMap["<Root>/Data Store Write"] = {sid: "keypad_DONE:149"};
	this.sidHashMap["keypad_DONE:149"] = {rtwname: "<Root>/Data Store Write"};
	this.rtwnameHashMap["<Root>/Data Store Memory"] = {sid: "keypad_DONE:147"};
	this.sidHashMap["keypad_DONE:147"] = {rtwname: "<Root>/Data Store Memory"};
	this.rtwnameHashMap["<Root>/Data Type Conversion"] = {sid: "keypad_DONE:143"};
	this.sidHashMap["keypad_DONE:143"] = {rtwname: "<Root>/Data Type Conversion"};
	this.rtwnameHashMap["<Root>/Digital Output"] = {sid: "keypad_DONE:123"};
	this.sidHashMap["keypad_DONE:123"] = {rtwname: "<Root>/Digital Output"};
	this.rtwnameHashMap["<Root>/Digital Output1"] = {sid: "keypad_DONE:142"};
	this.sidHashMap["keypad_DONE:142"] = {rtwname: "<Root>/Digital Output1"};
	this.rtwnameHashMap["<Root>/Display1"] = {sid: "keypad_DONE:118"};
	this.sidHashMap["keypad_DONE:118"] = {rtwname: "<Root>/Display1"};
	this.rtwnameHashMap["<Root>/Display2"] = {sid: "keypad_DONE:117"};
	this.sidHashMap["keypad_DONE:117"] = {rtwname: "<Root>/Display2"};
	this.rtwnameHashMap["<Root>/Display3"] = {sid: "keypad_DONE:119"};
	this.sidHashMap["keypad_DONE:119"] = {rtwname: "<Root>/Display3"};
	this.rtwnameHashMap["<Root>/Display5"] = {sid: "keypad_DONE:122"};
	this.sidHashMap["keypad_DONE:122"] = {rtwname: "<Root>/Display5"};
	this.rtwnameHashMap["<Root>/Display6"] = {sid: "keypad_DONE:129"};
	this.sidHashMap["keypad_DONE:129"] = {rtwname: "<Root>/Display6"};
	this.rtwnameHashMap["<Root>/Display8"] = {sid: "keypad_DONE:141"};
	this.sidHashMap["keypad_DONE:141"] = {rtwname: "<Root>/Display8"};
	this.rtwnameHashMap["<Root>/Gain"] = {sid: "keypad_DONE:140"};
	this.sidHashMap["keypad_DONE:140"] = {rtwname: "<Root>/Gain"};
	this.rtwnameHashMap["<Root>/S-Function Builder"] = {sid: "keypad_DONE:144"};
	this.sidHashMap["keypad_DONE:144"] = {rtwname: "<Root>/S-Function Builder"};
	this.rtwnameHashMap["<Root>/Scope"] = {sid: "keypad_DONE:120"};
	this.sidHashMap["keypad_DONE:120"] = {rtwname: "<Root>/Scope"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
